### ISSUE TITLE
doesn't work on turbowarp

### ISSUE THREAD

**Issue by ghost** [Samq64/scratch-extensions#2]
when you add this to turbowarp it doesn't install correctly. 

it throws the error:
_Uncaught TypeError: Cannot read properties of undefined (reading 'extensionManager')
  at samq64.github.io/scratch-extensions/MouseCursor.js:68:55
  at samq64.github.io/scratch-extensions/MouseCursor.js:71:3_

**Comment by Samq64** [comment]
The extension isn't really being maintained and it never worked in in TurboWarp because TurboWarp extensions have a very strict sandbox and until it's improved, you'll probably just have to load it in [E羊icques](https://sheeptester.github.io/scratch-gui/) as a plugin (`?load_plugin=https://...`) instead.

**Comment by Samq64** [comment]
This extension isn't really maintained and it never worked in Turbowarp because it's unsandboxed.

**Comment by Samq64** [comment]
It looks it will soon work on TuroWarp: https://extensions.turbowarp.org/

**Comment by Samq64** [comment]
There are some breaking changes, but the extension just got merged into TurboWarp's custom extension library at https://extensions.turbowarp.org/ and should be able to be loaded from the main site soon.
